### ISSUE TITLE
Windows still not working

### ISSUE THREAD

**Issue by SimonDanisch** [MichaelHatherly/Tectonic.jl#7]
It looks like 0.5.1 was supposed to fix the windows build, but it still doesn't seem fixed.
When I look at the artifact url, I see it repackages tectonic-0.5.1+1-x86_64-w64-mingw32.tar, maybe that should rather be https://github.com/tectonic-typesetting/tectonic/releases/download/continuous/tectonic-0.5.1+20210608-x86_64-pc-windows-msvc.zip, which does work indeed.

**Comment by MichaelHatherly** [comment]
0.5.2 will fix it as far as I understand, once it's properly released. I wasn't planning to use any of their "continuous deployment" versions.

**Comment by SimonDanisch** [comment]
Ah ok ... so that release wasn't actually the one to fix it ;) Cool! I'll leave this issue open to track the issue on windows.

**Comment by MichaelHatherly** [comment]
Yeah, I just release in lock step with upstream so that there's always a corresponding version rather than skipping anything.
